In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
% matplotlib inline
np.set_printoptions(formatter={'float_kind':lambda x: "%.2f" % x})

In [2]:
train_df= pd.read_csv('counterfeit_train.csv')
train_df['label'] = 'train'
test_df=pd.read_csv("counterfeit_test.csv")
test_df['label'] = 'test'

In [3]:
train_df=train_df.drop('Medicine_ID',axis=1)

In [4]:
test_df=test_df.drop('Medicine_ID',axis=1)

In [5]:
#Concat the datasets
concat_df = pd.concat([train_df , test_df])

In [6]:
features_df = pd.get_dummies(concat_df,columns=['DistArea_ID',"Active_Since",'Medicine_Type','SidEffect_Level','Area_Type',
                                               'Area_City_Type','Area_dist_level'])

In [7]:
type(features_df)

pandas.core.frame.DataFrame

In [8]:
train_df

Counterfeit_Weight DistArea_ID  Active_Since  Medicine_MRP  \
0                 13.100     Area046          1995      160.2366   
1                    NaN     Area027          1983      110.4384   
2                  9.025     Area046          1995      259.4092   
3                 11.800     Area046          1995       99.9830   
4                    NaN     Area019          1983       56.4402   
5                  8.775     Area045          2000      165.5656   
6                 18.000     Area018          2007      156.9102   
7                  7.680     Area013          1985      154.3470   
8                 18.550     Area046          1995      107.3068   
9                  9.510     Area013          1985      161.1392   
10                 9.270     Area018          2007      182.3422   
11                18.150     Area018          2007      104.0120   
12                   NaN     Area019          1983      118.5280   
13                13.900     Area017          2005      182.8764   
14                20.300     Area010          1996      238.5720   
15                22.550     Area013          1985      129.6756   
16                13.300     Area046          1995      132.2388   
17                21.650     Area010          1996       93.0276   
18                20.050     Area013          1985      224.4218   
19                15.450     Area035          2002      136.6046   
20                19.050     Area045          2000      150.2838   
21                13.900     Area035          2002       61.0982   
22                16.400     Area035          2002      253.4512   
23                11.400     Area017          2005      163.7656   
24                20.900     Area046          1995      115.9964   
25                13.400     Area045          2000       66.5614   
26                18.800     Area017          2005      182.0738   
27                22.000     Area035          2002      163.1366   
28                11.600     Area018          2007      184.7422   
29                13.600     Area018          2007      126.7834   
...                  ...         ...           ...           ...   
6788              19.300     Area046          1995      169.2604   
6789              16.650     Area045          2000       75.5168   
6790              18.800     Area010          1996      155.1102   
6791                 NaN     Area027          1983      189.0028   
6792              18.050     Area018          2007       84.0038   
6793               6.740     Area045          2000      188.4370   
6794                 NaN     Area019          1983       51.8796   
6795              10.495     Area035          2002       62.3666   
6796              19.150     Area013          1985      222.2560   
6797              12.650     Area017          2005      192.2608   
6798                 NaN     Area019          1983      195.4898   
6799              21.000     Area049          1997      188.3660   
6800              11.300     Area049          1997      128.6440   
6801              16.650     Area017          2005      206.8768   
6802              19.650     Area046          1995      194.7266   
6803              19.650     Area046          1995       94.6882   
6804               9.900     Area017          2005      201.9530   
6805               9.050     Area017          2005      104.6436   
6806              11.950     Area017          2005       66.9272   
6807              14.400     Area045          2000      130.4782   
6808              20.650     Area017          2005      123.0518   
6809              12.650     Area046          1995       98.2856   
6810              16.100     Area018          2007      119.3570   
6811                 NaN     Area019          1983      102.1120   
6812              17.650     Area010          1996      135.1020   
6813               8.535     Area046          1995      204.1452   
6814              20.650     Area046          1995      235.10

In [9]:
# Split your data
train_df = features_df[features_df['label'] == 'train']
test_df = features_df[features_df['label'] == 'test']

In [10]:
# Drop your labels
train_df = train_df.drop('label', axis=1)
test_df = test_df.drop('label', axis=1)

In [11]:
train_df.head()

Availability_rating  Counterfeit_Sales  Counterfeit_Weight  Medicine_MRP  \
0             0.070422          1775.5026              13.100      160.2366   
1             0.013000          3069.1520                 NaN      110.4384   
2             0.060783          2603.0920               9.025      259.4092   
3             0.065555          1101.7130              11.800       99.9830   
4             0.248859           158.9402                 NaN       56.4402   

   DistArea_ID_Area010  DistArea_ID_Area013  DistArea_ID_Area017  \
0                    0                    0                    0   
1                    0                    0                    0   
2                    0                    0                    0   
3                    0                    0                    0   
4                    0                    0                    0   

   DistArea_ID_Area018  DistArea_ID_Area019  DistArea_ID_Area027  \
0                    0                    0                    0   
1                    0                    0                    1   
2                    0                    0                    0   
3                    0                    0                    0   
4                    0                    1                    0   

            ...             Area_Type_DownTown  Area_Type_Industrial  \
0           ...                              1                     0   
1           ...                              0                     0   
2           ...                              1                     0   
3           ...                              1                     0   
4           ...                              0                     0   

   Area_Type_MidTownResidential  Area_City_Type_Tier 1  Area_City_Type_Tier 2  \
0                             0                      1                      0   
1                             0                      0                      0   
2                             0                      1                      0   
3                             0                      1                      0   
4                             1                      1                      0   

   Area_City_Type_Tier 3  Area_dist_level_High  Area_dist_level_Medium  \
0                      0                     0                       0   
1                      1                     0                       1   
2                      0                     0                       0   
3                      0                     0                       0   
4                      0                     0                       0   

   Area_dist_level_Small  Area_dist_level_Unknown  
0                      1                        0  
1                      0                        0  
2                      1                        0  
3                      1                        0  
4                      1                        0  

[5 rows x 52 columns]

In [12]:
train_df['Counterfeit_Sales1']=train_df['Counterfeit_Sales']
train_df=train_df.drop(['Counterfeit_Sales'],axis=1)

In [13]:
x=train_df.iloc[:,0:-1].values
y=train_df.iloc[:,-1].values

In [14]:
#data preprocessing

In [15]:
from sklearn.preprocessing import Imputer

In [16]:
imputer=Imputer()

In [17]:
imputer=imputer.fit(x[:,[0,1,2]])

In [18]:
x[:,[0,1,2]]=imputer.transform(x[:,[0,1,2]])

In [19]:
print(x)

[[0.07 13.10 160.24 ..., 0.00 1.00 0.00]
 [0.01 14.12 110.44 ..., 1.00 0.00 0.00]
 [0.06 9.03 259.41 ..., 0.00 1.00 0.00]
 ..., 
 [0.11 20.00 193.63 ..., 0.00 0.00 1.00]
 [0.10 10.18 162.87 ..., 0.00 0.00 1.00]
 [0.12 7.93 177.55 ..., 1.00 0.00 0.00]]


In [20]:
#splitting the dataset

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=1)

In [23]:
x_train

array([[0.15, 7.71, 138.47, ..., 0.00, 1.00, 0.00],
       [0.07, 14.12, 175.75, ..., 1.00, 0.00, 0.00],
       [0.16, 8.51, 112.93, ..., 0.00, 1.00, 0.00],
       ..., 
       [0.14, 12.80, 111.14, ..., 0.00, 1.00, 0.00],
       [0.03, 15.45, 207.21, ..., 0.00, 0.00, 1.00],
       [0.11, 14.12, 264.17, ..., 1.00, 0.00, 0.00]])

In [24]:
y_train

array([1130.34, 5375.48, 2266.20, ..., 2224.25, 505.82, 3410.71])

In [25]:
del(x_train)
del(y_train)

In [26]:
#Fitting Random Forrest Regression to the dataset

In [27]:
from sklearn.ensemble import RandomForestRegressor

In [28]:
regressor=RandomForestRegressor(n_estimators=10,criterion='mae',random_state=1)

In [29]:
regressor.fit(x,y)

RandomForestRegressor(bootstrap=True, criterion='mae', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_split=1e-07, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=10, n_jobs=1, oob_score=False, random_state=1,
           verbose=0, warm_start=False)

In [30]:
#Predicting on test

In [31]:
y_pred=regressor.predict(x_test)

In [32]:
y_pred

array([2867.41, 1012.43, 5151.51, ..., 791.32, 631.79, 3082.47])

In [33]:
y_test

array([3053.17, 1038.46, 5828.23, ..., 803.43, 640.31, 3112.43])

In [34]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_pred)

298.6197347683285

In [35]:
# Now predicting for unknown

In [36]:
test_df=test_df.drop(['Counterfeit_Sales'],axis=1)

In [37]:
len(test_df.columns)

51

In [38]:
x_test1=test_df.iloc[:,0:52].values
x_test1

array([[0.11, nan, 85.53, ..., 1.00, 0.00, 0.00],
       [0.14, 13.45, 257.15, ..., 0.00, 0.00, 1.00],
       [0.14, 7.10, 98.12, ..., 0.00, 0.00, 1.00],
       ..., 
       [0.19, 20.40, 182.74, ..., 0.00, 0.00, 1.00],
       [0.01, 20.00, 266.97, ..., 1.00, 0.00, 0.00],
       [0.10, 8.08, 238.77, ..., 0.00, 0.00, 1.00]])

In [39]:
from sklearn.preprocessing import Imputer

In [40]:
imputer=Imputer()

In [41]:
imputer=imputer.fit(x_test1[:,[1]])

In [42]:
x_test1[:,[1]]=imputer.transform(x_test1[:,[1]])

In [43]:
print(x_test1)

[[0.11 14.33 85.53 ..., 1.00 0.00 0.00]
 [0.14 13.45 257.15 ..., 0.00 0.00 1.00]
 [0.14 7.10 98.12 ..., 0.00 0.00 1.00]
 ..., 
 [0.19 20.40 182.74 ..., 0.00 0.00 1.00]
 [0.01 20.00 266.97 ..., 1.00 0.00 0.00]
 [0.10 8.08 238.77 ..., 0.00 0.00 1.00]]


In [44]:
y_pred2=regressor.predict(x_test1)

In [45]:
y_pred2

array([2449.89, 2977.74, 1667.51, ..., 3076.14, 3792.81, 3818.24])

In [46]:
test_df['Counterfeit_Sales']=y_pred2

In [47]:
test_df

Availability_rating  Counterfeit_Weight  Medicine_MRP  \
0                0.112747                 NaN       85.5328   
1                0.144446              13.450      257.1460   
2                0.144221               7.100       98.1172   
3                0.100388              18.300      135.3730   
4                0.022585                 NaN      112.8016   
5                0.074382              14.450      190.2976   
6                0.073134                 NaN      163.3656   
7                0.082101              17.150      226.9166   
8                0.094614                 NaN      225.0534   
9                0.027763              15.100      101.0172   
10               0.077607                 NaN       97.7198   
11               0.048579              10.900      254.7170   
12               0.120274               6.760      155.8786   
13               0.095798              18.900      171.7920   
14               0.104319                 NaN      241.0352   
15               0.019087              14.400      195.3898   
16               0.064367                 NaN       87.3644   
17               0.027568              19.050      168.4262   
18               0.158867              11.495      204.3794   
19               0.033664              17.650       61.1324   
20               0.127565              17.000      122.3202   
21               0.061135              10.495      118.0622   
22               0.056864               8.360       69.8904   
23               0.033680              13.800      207.5742   
24               0.088445               7.875      156.3444   
25               0.106918              20.500      200.1214   
26               0.052428              21.650      138.2678   
27               0.024181              15.950       64.1614   
28               0.013000                 NaN       97.9856   
29               0.048773               9.615      154.6444   
...                   ...                 ...           ...   
1675             0.077504              16.300       57.6060   
1676             0.104918              20.400      193.0608   
1677             0.043933              12.650       61.8008   
1678             0.145671              13.150      106.7726   
1679             0.046761              13.650      207.2426   
1680             0.113967              10.695       97.1856   
1681             0.051657              13.650      120.5570   
1682             0.076947              11.100      126.9492   
1683             0.037988              17.400      107.6410   
1684             0.086013                 NaN       77.8142   
1685             0.050853               6.105      136.5704   
1686             0.100763              16.400      231.8456   
1687             0.172721              17.800      154.8128   
1688             0.062017              19.400      139.0336   
1689             0.095140               7.065       47.5164   
1690             0.149984               8.190      202.9820   
1691             0.064644                 NaN      117.6622   
1692             0.036627              14.100      233.5404   
1693             0.099781              10.180      162.5682   
1694             0.051816              18.400      176.7842   
1695             0.134254              21.500      104.8752   
1696             0.112675              13.650      122.5518   
1697             0.013000              10.900      111.9990   
1698             0.032019              16.500      249.0248   
1699             0.070423              17.400      264.0356   
1700             0.050505                 NaN      136.5704   
1701             0.041118              21.300       57.0744   
1702             0.191273              20.400      182.7422   
1703             0.013000              20.000      266.9672   
1704             0.098982               8.080      238.7694   

      DistArea_ID_Area010  DistArea_ID_Area013  DistArea_ID_Area017  \
0                       0   

In [48]:
test_df.to_csv("test.csv",sep=',')